project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_API_TOKEN"

preserve_hierarchy: false

files: [
  {
    "source": "/locales/locales.pot",
    "translation": "/src/locales/%locale_with_underscore%.po",

    "languages_mapping": {
      "locale_with_underscore": {
        "de": "de",
        "es-ES": "es",
        "fr": "fr",
        "ja": "ja_JP",
        "ko": "ko",
        "nl": "nl",
        "pl": "pl",
        "pt-BR": "pt_BR",
        "zh-CN": "zh_CN",
        "zh-TW": "zh_TW"
      }
    }
  }
]
