name: Collect shell versions
on:
  workflow_call:
    outputs:
      non_deprecated_shell_versions:
        description: "The first output string"
        value: ${{ toJSON(jobs.collect-shell-versions.outputs.non_deprecated_shell_versions) }}

jobs:
  collect-shell-versions:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    outputs:
      non_deprecated_shell_versions: ${{ steps.extract-versions.outputs.non_deprecated_shell_versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Get @c8y/ngx-components, non-deprecated dist versions
        id: collect-shell-versions
        run: npm run collect-shell-versions

      - name: Extract versions
        id: extract-versions
        run: |
          echo "non_deprecated_shell_versions=${{ steps.collect-shell-versions.outputs.non_deprecated_shell_versions }}" >> $GITHUB_OUTPUT

      - name: Debug Output
        run: echo "non_deprecated_shell_versions=${{ steps.collect-shell-versions.outputs.non_deprecated_shell_versions }}" >> $GITHUB_ENV
