name: Collect shell versions
on:
  pull_request: # TODO: change workflow trigger

permissions:
  contents: read

jobs:
  collect-shell-versions:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    name: Get shell versions by tags

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Get @c8y/ngx-components, non-deprecated dist versions
        id: check-deprecated
        run: npm run collect-shell-versions

      - name: Use non-deprecated versions
        run: |
          echo "Non-deprecated Versions: ${{ steps.check-deprecated.outputs.non_deprecated_shell_versions }}"

      # further should run in loop for each shell version

#      - name: Build
#        run: npm run build:ci
#
#      - name: Upload build artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: build
#          if-no-files-found: error
#          retention-days: 5
#          path: |
#            dist/apps/sag-pkg-community-plugins/**
