name: Pull request
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  cypress:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    name: Cypress tests
    container:
      image: cypress/browsers:node16.16.0-chrome107-ff107
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - uses: sibiraj-s/action-eslint@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          eslint-args: '--quiet'
          extensions: 'html,ts'
          annotations: true

      - name: Add commit hash to version
        run: |
          npm version prepatch --no-git-tag-version --preid $(git rev-parse --short HEAD)

      - name: Build
        run: npm run build:ci

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          retention-days: 5
          path: |
            dist/apps/sag-pkg-community-widgets/**

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run http-server
          install: false
          wait-on: 'http://localhost:9000/apps/sag-pkg-community-widgets/index.html'
          browser: chrome
          record: false
          config-file: cypress.config.ts

      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          retention-days: 5
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload cypress videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          retention-days: 5
          name: cypress-videos
          path: cypress/videos
