name: Release assets
on:
  release:
    types: [published, released, prereleased]

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Set RELEASE_VERSION env variable
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build:ci

    - name: Zip build
      run: |
        cd dist/apps/sag-pkg-community-widgets
        zip -r -q ../../../cumulocity-community-widgets-${{ env.RELEASE_VERSION }}.zip *
        cd ../../..
        rm -r dist/apps

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: cumulocity-community-widgets-${{ env.RELEASE_VERSION }}.zip
